# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('primer_apellido', models.CharField(blank=True, max_length=255)),
                ('segundo_apellido', models.CharField(blank=True, max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('telefono_fijo', models.CharField(blank=True, max_length=255)),
                ('telefono_movil', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
