# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_auto_20161215_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
