# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_contacto_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
