# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0004_contacto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contacto',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=255),
        ),
        migrations.AddField(
            model_name='contacto',
            name='puesto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
